export declare const is: (val: unknown, type: string) => boolean;
export declare const isDef: <T = unknown>(val?: T | undefined) => val is T;
export declare const isUnDef: <T = unknown>(val?: T | undefined) => val is T;
export declare const isObject: (val: any) => val is Record<any, any>;
export declare const isEmpty: <T = unknown>(val: T) => val is T;
export declare const isDate: (val: unknown) => val is Date;
export declare const isNull: (val: unknown) => val is null;
export declare const isNullAndUnDef: (val: unknown) => val is null | undefined;
export declare const isNullOrUnDef: (val: unknown) => val is null | undefined;
export declare const isNumber: (val: unknown) => val is number;
export declare const isPromise: <T = any>(val: unknown) => val is Promise<T>;
export declare const isString: (val: unknown) => val is string;
export declare const isFunction: (val: unknown) => val is Function;
export declare const isBoolean: (val: unknown) => val is boolean;
export declare const isRegExp: (val: unknown) => val is RegExp;
export declare const isArray: (val: any) => val is any[];
export declare const isWindow: (val: any) => val is Window;
export declare const isElement: (val: unknown) => val is Element;
export declare const isMap: (val: unknown) => val is Map<any, any>;
export declare const isServer: boolean;
export declare const isClient: boolean;
export declare const isUrl: (path: string) => boolean;
export declare const isDark: () => boolean;
export declare const isImgPath: (path: string) => boolean;
export declare const isEmptyVal: (val: any) => boolean;
